#!/bin/sh

curl -L -o Hard.png https://data.kitware.com/api/v1/file/57718cc48d777f1ecd8a883f/download
cp Hard.png examples/
curl -L -o Easy1.png https://data.kitware.com/api/v1/file/576ad39b8d777f1ecd6702f2/download
cp Easy1.png examples/
